### ISSUE TITLE
feat: add support for post and page permalinks in Next.js app

### ISSUE THREAD

**Issue by ginatrapani** [postlight/headless-wp-starter#10]
Add support for `/post/:post_slug:` and `/page/:page_slug:` links that load the correct post and page, respectively.

**Comment by morgvanny** [comment]
I’m thinking of adding a post page that will dynamically load whatever post was clicked on the index page (that link would have to be changed to relative so it doesn’t take you to the wp-json). Is this the type of thing you’d want to add? If so, would it be a good idea to use Express to handle routing more easily?

**Comment by ginatrapani** [comment]
yes @morgvanny that sounds great! Express makes sense. I'm just learning Next.js myself, but that seems to be the recommendation here: https://learnnextjs.com/basics/server-side-support-for-clean-urls

**Comment by morgvanny** [comment]
I've been reading through that as well. I've tried setting up express, and creating server side support for clean URLs, but I've run into a problem.

I had successfully tried using the post.link property to determine the path to use without server-side support, but that seems to break down once I'm in the server.js file trying to set up a route that should apply for all posts.

In the examples, it sets it up so that posts have paths like p/post-name. So then any time the url starts with p/ express will know to use the post.js file. I think we'd rather not do it that way, and it'd be best if we could mimic the same urls that a regular WordPress site would use. Seems like it'd be ideal if changing the permalink structure in WordPress would change the way routing is done in the Next.js app - but I'm not sure if that's practical or not? It seems like it's either that, or we make the decision on how paths will look, I guess.

**Comment by ginatrapani** [comment]
> Seems like it'd be ideal if changing the permalink structure in WordPress would change the way routing is done in the Next.js app - but I'm not sure if that's practical or not? 

I love this idea, and I believe it's totally possible/practical. We'd need to expose the permalink structure set in WP in the API, and then the app could parse it and set up the routes based on it.

> It seems like it's either that, or we make the decision on how paths will look, I guess.

I think we break that out into a separate task, and in the first iteration, just choose a simple, hardcoded route. I'd recommend `/post/:post_slug:` and `/page/:page_slug:` to start. What do you think? Then we can file a separate ticket for supporting custom permalink structures.

**Comment by ginatrapani** [comment]
I'm gonna go ahead and edit this ticket to narrow the scope to just support for page and post permalinks, and then we can create follow-up tickets as tasks fall out of that so we can make small, iterative progress.
