### ISSUE TITLE
URL Structure

### ISSUE THREAD

**Issue by fmixell** [postlight/headless-wp-starter#114]
I love this repo! My only issue is that I want to change the URL structure. Having yoursite.com/pages/page isn't good for SEO especially if you're taking an existing site and rebuilding it into a react js app. 

Is it possible to rewrite the server.js to make it so pages are shown like this "example.com/about" instead of "example.com/pages/about"

**Comment by pennjammin** [comment]
Hey there! So, I was able to get this working with the following code:
`server.get("/:slug", (req, res) => {
            const actualPage = "/page";
            const queryParams = { slug: req.params.slug, apiRoute: "page" };
            const actualPageBlog = "/blog";
            const queryParamsBlog = { slug: req.params.slug, apiRoute: "post" };
            if(req.params.slug === "blog") {
              app.render(req, res, actualPageBlog, queryParamsBlog);
            }
            else {
              app.render(req, res, actualPage, queryParams);
            }
        });`
in the server.js file. Note that in this scenario I have a blog.js in the pages folder. This essentially exempts the blog page and allows it to render instead of 404ing like localhost:3000/page would (I have this setup to throw a 404 in page.js). I am sure you could write it as a switch instead or find a more efficient way as you add exemptions for whatever you would like in your pages folder. Either way, if someone with more insight wants to chime in that would be great but for now this will allow you to structure things as they normally would be in WordPress. Let me know if you want me to clarify anything, haha, I am not the best at articulating things :)

**Comment by fmixell** [comment]
This solution is working for me.. Maybe you should do a pull request?

**Comment by omattman** [comment]
Hi @fmixell 

I was playing around with this as well and found the issue in the following Link setup (this issue is first spotted in the [index.js](https://github.com/postlight/headless-wp-starter/blob/master/frontend/pages/index.js) file)

The <Link> registers the links slug setup with the following: `as={'/page/${page.slug}'}`

Which adds the page, post, category slugs to your URL structure. This can be corrected by removing page and simply having: `as={'/${page.slug}'}`

Furthermore this setup also occurs in the Menu.js file, where you will have to go through this to edit it correctly.

**Comment by gopolar** [comment]
I am migrating my Wordpress website to Next.js. Can anyone advise how I can keep the URLs without "/post/" or "/page/"?

I want to keep the URL structure as following :
"example.com/awesome-post" 
"example.com/awesome-page"
