### ISSUE TITLE
'robo' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by samiti3d** [postlight/headless-wp-starter#121]
I am using PowerShell to yarn install it shows
` $ chmod +x install.sh && chmod +x mysql_config.sh && ./install.sh`
but it seems not run chmod in windows 10, so can anyone introduce me to install on Windows 10. I stuck like hours.

**Comment by george-haddad** [comment]
Hi there, due to the limitations on such programs like [wp-cli](https://wp-cli.org/) even if the scripts had powershell equivalents we would still run into problems. One very nice solution is to enable the [Linux subsystem on Windows 10 ](https://docs.microsoft.com/en-us/windows/wsl/install-win10) and install the whole thing there.

**Comment by samiti3d** [comment]
Okay, Thank You, I am so happy. practice as  [this instruction ](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
