### ISSUE TITLE
Error establishing a database connection after restarting

### ISSUE THREAD

**Issue by annamirakk** [postlight/headless-wp-starter#169]
Hi! I've noticed similar issues logged, but couldn't find an answer that would help. I've just installed the latest version of headless-wp-starter with Docker, made sure everything works, then restarter my machine and can't connect to the database. I'm on MacOS Mojave 10.14.2, below are the commands I ran from the project directory:
`mysql.server start`
`docker exec -it wp-headless /bin/bash`
`cd frontend && yarn start`

I see "Compiled successfully" in the console, but an error on the frontend:
"invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at http://localhost:8080/wp-json/menus/v1/menus/header-menu reason: Unexpected token < in JSON at position 0
at /var/www/html/frontend/node_modules/node-fetch/lib/body.js:48:31
at 
at process._tickCallback (internal/process/next_tick.js:188:7)"

and an "Error establishing a database connection" error in the backend. Any help is much appreciated!

**Comment by modelm** [comment]
`Unexpected token < in JSON at position 0` usually indicates there's some markup instead of just JSON, e.g. if there was some error with PHP code it may output with markup resulting in invalid JSON. To find out what that is, examine the WP API response in the developer console or make the request directly in the browser. If you still have trouble feel free to re-open this.
