### ISSUE TITLE
Issue displaying Custom Fields

### ISSUE THREAD

**Issue by annamirakk** [postlight/headless-wp-starter#170]
I've created a custom field and added some custom text to a post (see screenshot), but don't see my custom text on the frontend. What are the steps I'm missing? Thanks!

Admin panel:
![custom_text](https://user-images.githubusercontent.com/41708321/50363122-356d6e80-051f-11e9-8e8e-06396d75a0f0.png)

Frontent:
![frontend](https://user-images.githubusercontent.com/41708321/50363128-3900f580-051f-11e9-93ed-3400872c02e7.png)

**Comment by annamirakk** [comment]
Figured it out, add something like `{this.props.post.acf.test_cf_text}` to the component, post.js in my case. Hope this helps!

**Comment by ProjectKarol** [comment]
Helps I already  start doing the same 👍 :)

**Comment by annamirakk** [comment]
Reopening this issue. The above only works this was as long as the prop is inside <Layout />, but I haven't been able to access those variables otherwise. I'd like to add logic based on a custom variable assigned to a post. Can I access ACF variables inside 
`    static async getInitialProps(context) {
...
    }`
for instance?

**Comment by jacobmishkin** [comment]
@annamirakk yes, you can destructure the post object for the acf endpoint. What are you trying to do?

**Comment by annamirakk** [comment]
@jacobmishkin for example I'm trying to build a [donut chart](https://www.chartjs.org/docs/latest/charts/doughnut.html#data-structure) based on some variables created with ACF using chart.js . So I do something like this:

`componentDidMount() {
        const allData = {
            datasets: 
            [{
                data: [35, 14, 23, 16],   // these data points are different ACF variables: data_green, data_blue, etc
                backgroundColor: [
                    "#7B4DD8",  // these colors should ideally be ACF variables as well
                    "#FF5679",
                    "#53C38C",
                    "#0056E6"
                ]
            }]
        };
        const allDonut = new Chart(document.getElementById("allDonut"), {
            type: 'doughnut',
            data: allData
        });
}`

Another example with the same data points: I need to show only one of them on each page of a certain type depending on another variable specific to that page. Something like 
`if ({this.props.page.acf.data_green} === 'green')   // variable specific to a page
{ 
<p className="green">{this.props.page.acf.data_green}</p>  
 }`

Hope that makes sense!

**Comment by jacobmishkin** [comment]
This makes total sense. I would look at using this chart.js for react module: 

https://github.com/jerairrest/react-chartjs-2 

This will hopefully make rendering the chart easier. 

There are a couple of ways you can render different data. You can use the inline conditional operator by setting a bool value prop to the component then render that component not sure on how manny variables you're using. 
 
How manny pages are you working with? If you need one chart each new page you could use getinitailprops() on each of your pages in the pages folder and render that out in your component. Fetch the data in the page.js file, not the component. If there is something I missed, please feel free to let me know. 

I hope this helps.

**Comment by annamirakk** [comment]
@jacobmishkin thank you for a quick response and a link, I'll take a look! However chart.js is only one example, and I need to do a bunch of different things with ACF variables outside 
```
render() {
    return (
        <Layout>
            ...
        </Layout>
        );
    }
``` 
like the second example from the post above. My problem is I can't seem to access those variables outside <Layout />. I tried to fetch that data in getInitialProps() in post.js (as that file also seems to work for pages), but unsuccessfully. Would you be able to post the correct way of doing so here?

**Comment by jacobmishkin** [comment]
Oh no worries, it's all good. 

You can't access anything outside of the layout component, because everything is a child of the layout. 
```javascript

import Header from "./Header";
import Footer from "./Footer";

const layoutStyle = {
    margin: 20,
    padding: 20
};

const Layout = props => (
    <div style={layoutStyle}>
        <Header />
        {props.children}
        <Footer />
    </div>
);

export default Layout;
```
So props.children is everything. You would need to modify this component.  Every .js file inside of the pages folder is a new page. So post.js in my pages folder will create the route: "www.blah.com/post" 
If you need a new page create a new file in the pages folder. I recommend naming them in lower case as they will become the name used in the url route. 

Here is a sample blog page in my pages folder the route is www.blah.com/blog  file: 
```javascript 

class Post extends Component {
  static async getInitialProps(context) {
    const { slug, apiRoute } = context.query;
    const res = await fetch(
      `${Config.apiUrl}/wp-json/postlight/v1/${apiRoute}?slug=${slug}`
    );
    const post = await res.json();
    return { post };
  }

  render() {
    const { post } = this.props;

    if (!post.title) return <Error statusCode={404} />;

    return (
      <Layout {...this.props}>
          <Hero tagline={post.title.rendered} />
           <section className="page_container post">
           <Image
              image={post.acf.image}
              alt="Custom Post Types using the REST API and React"
            />
           <div dangerouslySetInnerHTML={{ __html: post.content.rendered }}></div>
        </section>
      </Layout>
    );
  }
}

export default PageWrapper(Post);
```

There are a couple of things I've added to the original template. After the render I'm destructuring the post object out of this.props so I don't need to write this.props. Second thing is I'm spreading the props into the layout component due to how I create menus this will create props at the highest level of the app and can pass props down to any component. Outside of what I'm pulling in, It's basically the same as the original post.js.  

To help with the second issue, I'd create the 4 pages in the pages folder. I'd also create a new <Layout> component with the layout that you want for those four pages, and then wrap everything inside the custom layout component. Use getInitialProps on each page to get the data you want. Import the donut component from the chartjs-react library add the data to the props of the donut component. You should be good to go.  If not, please feel free to let me know. 

PS Not sure if you're using WPGraphQL or not, but fyi WP bootstraps itself on every request, so core is reloaded, plugins, and themes are also reloaded on each request. Secondly the REST API outputs entire payloads if you need them or not. When your deploy the backend make sure there is some heavy duty server side caching going on, if not your site can take a long time to first paint. You can monitor this in the network dev tools under TTFB.

**Comment by annamirakk** [comment]
Thank you so much @jacobmishkin ! Looks helpful. I won't get to work on it for a few days, but hopefully that's enough info.

**Comment by jacobmishkin** [comment]
It really depends on your routing. Each file in the pages folder is a route. i.e. landingpage.com/custom
if you create a custom.js file in the pages folder. This is what NextJs does. 

getInitialProps is only a lifecycle and data fetching method for files in the pages folder. I mainly use this method for fetching data. If you use one page as a template you'll need to have either have multiple requests(multiple fetch calls) which is not ideal, due to the nature of the WP REST API. WP bootstrap's it's self on each request. Meaning WP reloads core, plugins, and themes on each request, so each time you 
```
// WP reloads and runs core, plugins, themes once because this is the first request. 
 const res = await fetch(
            `${Config.apiUrl}/wp-json/postlight/v1/${apiRoute}?slug=${slug}`
        );
 const post = await res.json();

// WP reloads and runs core, plugins, themes again because this is the second request. 
 const resCustom = await fetch(
            `${Config.apiUrl}/wp-json/postlight/v1/${apiRoute}?slug=${slug}`
        );
 const post = await resCustom.json();
// WP reloads and runs core, plugins, themes twice because we have two requests. 
```
This issue will create major load issues, It's a bummer. 

So if you have only one JS file in your pages folder and due multiple requests you will run into this issue. This is why outside of the routing, I would suggest using 4 JS files for 4 pages. Ideally one request per page, if possible. 

By template do you mean base CSS layout? Also not sure what you mean by every page that's a child of /landing-page should use pages/custom.js to render"? can you explain upon that. If it's just CSS layouts I'd make a custom layout component in your components folder, create the styles there then wrap the children components you want to use in that custom layout. here is a quick example: 

```
import Header from "./Header";
import Footer from "./Footer";

const layoutStyle = {
    margin: 20,
    padding: 20
};

const Layout = props => (
    <div style={layoutStyle}>
        <Header />
        {props.children}
        <Footer />
    </div>
);

export default Layout;
```
Above is the base layout component. 

Below is a Custom Layout
```
import Header from './Header';
import Footer from './Footer';
import Charts from './Charts';

const layoutStyle = {
  margin: 20,
  padding: 20
};

const mainLayout = {
  display: 'grid',
  gridTemplateColumns: '70% 30%'
};

const CustomLayout = props => (
  <div style={layoutStyle}>
    <Header />
    <main style={mainLayout}>
      <section>{props.children}</section>
      <aside>
        <Charts />
      </aside>
    </main>
    <Footer />
  </div>
);

export default CustomLayout;
```

then in any page you want a chart you'd have this: 

```
            <CustomLayout {...this.props}>
                <Menu menu={this.props.headerMenu} />
                <h1>I'm the Post</h1>
                  <div>
                      <p>More stuff here!!</p> 
                 </div>
            </CustomLayout>
```

I hope this helps.

**Comment by annamirakk** [comment]
@jacobmishkin thank you! If I should create a js file in /pages for each page, how do I make sure each of those pages fetch the right content? Let's say I use pages/index.js for my landing page, for that I use the following:

```javascript
const pageRes = await fetch(
            `${Config.apiUrl}/wp-json/postlight/v1/page?slug=landing-page`
        );
```

That works, but when I do the same thing in other pages/* files it doesn't seem to work. Let's say I have an "About" page in WP admin and its slug is `about`, if I understand correctly I need to create pages/about.js for it and it would look something like this:

```javascript
import Layout from "../components/Layout.js";
import React, { Component } from "react";
import fetch from "isomorphic-unfetch";
import Error from "next/error";
import PageWrapper from "../components/PageWrapper.js";
import Menu from "../components/Menu.js";
import { Config } from "../config.js";

class About extends Component {
    static async getInitialProps(context) {
        const { slug, apiRoute } = context.query;
        const aboutRes = await fetch(
            `${Config.apiUrl}/wp-json/postlight/v1/page?slug=about`
        );
        const about = await aboutRes.json();
        return { about };
    }

    render() {
        if (!this.props.about.title) return <Error statusCode={404} />;

        return (
            <Layout>
                <Menu menu={this.props.headerMenu} />
                <h1>{this.props.about.title.rendered}</h1>
                <div
                    dangerouslySetInnerHTML={{
                        __html: this.props.about.content.rendered
                    }}
                />
            </Layout>
        );
    }
}

export default PageWrapper(About);
``` 

Though that doesn't seem to work. Please help, thanks!

**Comment by annamirakk** [comment]
@jacobmishkin nevermind, made that work!

**Comment by jacobmishkin** [comment]
Awesome!! I'm glad you got it working!
