### ISSUE TITLE
Preview: Unhandled Rejection

### ISSUE THREAD

**Issue by NicolaSansom** [postlight/headless-wp-starter#206]
I have just installed this starter kit have not yet made any changes to the code and tried to update the simple post that is there out of the box, clicked preview doing so results in: 

![Image 2019-03-25 at 5 14 49 pm](https://user-images.githubusercontent.com/17367104/54939914-97c07b80-4f21-11e9-88ad-e92e7df4f603.png)

Steps to repo: 
1. Have backend & frontend running locally
2. Go to http://localhost:8080/wp-admin/post.php?post=1&action=edit 
2. Update post
3. Click preview

I also tried updating a page and get the same issue when previewing

Cheers
Nicola

**Comment by cordial** [comment]
+1

**Comment by Emiliano-Bucci** [comment]
Hi to all! Me too i'm getting `rest_cookie_invalid_nonce` using the example provided by `postlight` or here https://medium.com/kata-engineering/headless-wordpress-next-js-what-we-learned-c10abdf80f6a;

Is there a fix for this??
Thanks!

**Comment by jonwrona** [comment]
Same issue here, has a fix been found yet? As far as I understand the previews aren't supposed to use a `getInitialProps` so it's weird that the `PageWrapper` requires calling one. I tried to only call `getInitialProps` when it is available, but then the frontend errors because a post wasn't grabbed.

**Comment by magidmroueh** [comment]
this issue will be solved when this [PR](https://github.com/postlight/headless-wp-starter/pull/229) is merged.
