### ISSUE TITLE
Most of this entire package doesn't work.

### ISSUE THREAD

**Issue by MitchEff** [postlight/headless-wp-starter#223]
Okay, so using Docker doesn't work - it couldn't install mysql, then couldn't expose port 8080 etc etc etc. Ignoring that, we've been able to get the REST version running correctly by copying the `install_wordpress.sh` scripts and using those.

The GraphQL one doesn't work either. This plugin version is incorrect: `https://github.com/wp-graphql/wp-graphql-jwt-authentication/archive/v0.3.1.zip`, as DataSource::resolve_user() now expects 2 params, rather than one. Fixing the plugin version now returns an authToken, but the token itself doesn't work, and you can't log in.

Are any humans _actually_ using this, or is it sort of too good to be true?

**Comment by jonwrona** [comment]
I've had a lot of issues getting this up and running but I think I'm at a point saying it's working for me. Step 1 was getting the REST version working, which someone recommended switching from `mysql-client` to `mariadb-client` in the package.json. That worked for me. I never got the graphql version running because of issues with the menus, but I didn't plan on using graphql anyway.

After that I had a TON of issues with the post preview. If you run into that as well, I had to modify a few things.

In the `admin.php` file, I modified the `set_headless_preview_link` function to this:
```
function set_headless_preview_link( $link ) {
  // get_the_ID is returning the revision ID, not the post ID, I need the post ID 
  $revision_id = get_the_ID();
  $id = wp_get_post_parent_id($revision_id);
   return get_frontend_origin() . '/'
      . '_preview/'
      . $id . '/'
      . $revision_id . '/'
      . wp_create_nonce( 'wp_rest' );
}
```

For some reason `get_the_ID()` gets the revision ID not the post ID, so the api call on the preview page was breaking. After editing that, you'll need to edit the frontend's preview route.

In the `server.js` file I changed mine to:
```
server.get('/_preview/:id/:revision/:wpnonce', (req, res) => {
  const actualPage = '/preview';
  const queryParams = { id: req.params.id, revision: req.params.revision, wpnonce: req.params.wpnonce };
  app.render(req, res, actualPage, queryParams);
});
```

Finally, in the `pages/preview.js` file I modified the `componentDidMount` function to this:
```
componentDidMount() {
  const { url } = this.props;
  const { id, revision, wpnonce } = url.query;
  fetch(
    `${Config.apiUrl}/wp/v2/posts/${id}/revisions/${revision}?_wpnonce=${wpnonce}`,
    { credentials: 'include' }, // required for cookie nonce auth
  )
    .then(res => res.json())
    .then(res => {
      this.setState({
        post: res,
      });
    });
}
```

After all that it seems to be working fine for me, I am assuming there are other issues to work through, so if you run into anything else let me know, it's probably an issue for me as well.

**Comment by jwilson114** [comment]
I have been getting the same error, but the above hasn't completely solved it. Did you have any issues with CORS?

**Comment by magidmroueh** [comment]
mysql-client was changed to mariadb-client, and the graphql jwt authentication is now updated to latest version. after syncing your repo, if you still can’t login, please make sure to set the required secret keys: [REST & GraphQL JWT Authentication](https://github.com/postlight/headless-wp-starter#rest--graphql-jwt-authentication) section.
