### ISSUE TITLE
Do I have to deploy 2 projects?

### ISSUE THREAD

**Issue by balapa** [postlight/headless-wp-starter#49]
If I were to deploy the Next.js app, do I need 2 separate hostings? One for Next.js and the other for WordPress. Is there a way to run both projects in one hosting?

Thanks

**Comment by tyler-barnes** [comment]
One way to keep them on the same host is to deploy your WP install to a subdomain, for example wp.yoursite.com, and deploy the docker container to the main domain at yoursite.com. I don't think it's possible to have them both on the exact same url though.

**Comment by mantagen** [comment]
@balapa if you don't need SSR, then it would be possible to host your react bundle/index.html on a standard Wordpress server. I am certainly considering doing this.
My thinking is that you would just need to modify the `.htaccess` file so that all routes other than `/wp-json` respond with `index.html`
It would be a slightly variation from this project however, as the whole point in Next.js (I think) is the SSR

**Comment by steventsao** [comment]
Yeah, I'm also trying to deploy the WP backend, but by dockerizing it and deploying it to Now along with the frontend app. Will keep you posted on how it goes.
